// <auto-generated />
using Ems.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ems.Api.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221007233840_InitialDatabases")]
    partial class InitialDatabases
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Ems.Api.Data.DTO.EmployeeDto", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Age = 35,
                            Email = "Email@Email.com",
                            FirstName = "John",
                            LastName = "Doe"
                        });
                    
                    b.HasData(
                        new
                        {
                            EmployeeId = 2,
                            Age = 45,
                            Email = "example_2@Email.com",
                            FirstName = "John II",
                            LastName = "Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
